server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICES
          uri: lb://HOTELSERVICES
          predicates:
            - Path=/hotels/**

        - id: RATINGSERVICES
          uri: lb://RATINGSERVICES
          predicates:
            - Path=/ratings/**